# Generated by Django 4.1.3 on 2022-11-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.IntegerField(max_length=70)),
                ("empfname", models.CharField(max_length=70)),
                ("emplname", models.CharField(max_length=70)),
                ("empemail", models.EmailField(max_length=254)),
                ("empaddress", models.CharField(max_length=70)),
            ],
        ),
    ]
